// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigqedlwqkrtpgssmmep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ3FlZGx3cWtydHBnc3NtbWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjYzMDQsImV4cCI6MjA2NjA0MjMwNH0.QfENenZ0gLkeEBKtCv3m7ZLWgJBLi4oYKjsMx_5x7bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);